### ISSUE TITLE
Header bar fixes

### ISSUE THREAD

**Issue by cwardell** [codeforamerica/pdi-census#2]
A couple of thoughts on the header bar that currently has the data sets listed:
- Let's remove "Department" and just make sure that the full names of the departments are included in the first column (e.g., Albuquerque, NM Police Dept. v. Albuquerque)
- Rearrange the column/data set headers, such that Response Time comes either right before or after Pursuits
- For folks visiting this page, it's not clear what the data set headers really mean. Perhaps some rollover dialogs that explain what the particular data set is

**Comment by EdmundKorley** [comment]
We have suffixed state into department names and alphabetically sorted the dataset headers as well as added custom tooltips that provide some context on these headers.
